version: "3.2"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    env_file:
      - ./.env
    ports:
      - 3002:3002
    restart: "on-failure"
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_netguru_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    restart: "on-failure"
    
volumes:
  postgres_netguru_data:
